backend:
  name: git-gateway
  repo: bradysheridan/brit-saints
  branch: main

media_folder: "public/assets/uploads"

collections:
  - name: "saint"
    label: "Saint"
    folder: "src/content/serve/saints"
    create: true
    slug: "{{slug}}"
    fields:
      - label: "Title"
        name: "title"
        widget: "string"
        required: true
      - label: "Title (Arabic) - If left blank this will default to English title"
        name: "title_arabic"
        widget: "string"
        required: false
      - label: "Description"
        name: "description"
        widget: "markdown"
        required: true
      - label: "Description (Arabic) - If left blank this will default to English description"
        name: "description_arabic"
        widget: "markdown"
        required: false
      - label: "Preview text"
        name: "preview_text"
        widget: "markdown"
        required: true
      - label: "Preview text (Arabic) - If left blank this will default to English description"
        name: "preview_text_arabic"
        widget: "markdown"
        required: false
      - label: "Map layer"
        name: "map_layer"
        widget: "select"
        options: ["al-rijāl", "al-waliyāt", "al-waliyāt ghayr ma’rūf"]
        required: false
      - label: "Location"
        name: "location"
        widget: "object"
        summary: 'Location'
        required: false
        fields:
          - label: "Click on map"
            name: "map_geojson"
            widget: "map"
            type: "Point"
            required: false
          - label: "Enter latitude manually (this will take priority over map widget)"
            name: "manual_latitude"
            widget: "string"
            required: false
          - label: "Enter longitude manually (this will take priority over map widget)"
            name: "manual_longitude"
            widget: "string"
            required: false
